name: antibody-env
channels:
- nvidia
- pytorch
- bioconda
- conda-forge
- defaults
dependencies:
- black
- jupyter
- lightning
- pip
- python
- pytorch
- pytorch-cuda
- scikit-learn
- seaborn
- pip:
  - accelerate
  - py3Dmol
  - PyTDC
  - transformers
