name: antibody-env
channels:
- nvidia
- pytorch
- bioconda
- conda-forge
- defaults
dependencies:
- black
- python
- pip
- scikit-learn
- jupyter
- pytorch
- pytorch-cuda
- pip:
  - accelerate
  - py3Dmol
  - transformers
